version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  reviewers:
  - AuHau
  assignees:
  - AuHau
  ignore:
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.8
    - 2.5.9
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.25
    - 0.20.27
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ipfs-repo
    versions:
    - 8.0.0
    - 9.0.0
  - dependency-name: ipfs
    versions:
    - 0.53.2
    - 0.54.1
    - 0.54.2
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
  - dependency-name: ipfs-core-types
    versions:
    - 0.2.1
    - 0.3.0
  - dependency-name: ky
    versions:
    - 0.26.0
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: highlight.js
    versions:
    - 9.18.5
  - dependency-name: cids
    versions:
    - 1.1.5
  - dependency-name: ipfs-http-client
    versions:
    - 48.2.0
  - dependency-name: tasegir
    versions:
    - 1.9.1
  - dependency-name: codecov
    versions:
    - 3.8.1
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: "@hapi/hoek"
    versions:
    - 8.5.1
  - dependency-name: "@hapi/hapi"
    versions:
    - 18.4.1
  - dependency-name: "@hapi/accept"
    versions:
    - 3.2.4
  - dependency-name: "@hapi/subtext"
    versions:
    - 6.1.3
  - dependency-name: "@hapi/ammo"
    versions:
    - 3.1.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: electron
    versions:
    - 6.1.12
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: ipfsd-ctl
    versions:
    - 1.0.7
